// <auto-generated />
namespace TestingCoe800.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Created_RoleIDFk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Created_RoleIDFk));
        
        string IMigrationMetadata.Id
        {
            get { return "202001200841074_Created_RoleIDFk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
