//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingCoe800.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int Id { get; set; }
        public string StoreName { get; set; }
        public string Location { get; set; }
        public string ManagerIDFk { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime DateOpened { get; set; } = DateTime.Now;
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
